
  <?php
  include("../connect.php");
  date_default_timezone_set('Asia/Kolkata');
  $time_india_one = date("Y-m-d H:i:s");
  date_default_timezone_set('Asia/Gaza');
  $serviceDate = date("Y-m-d H:i:s");
  $msisdn = $_GET['msisdn'];
  $serviceId = "ARSH0125";
  $advName = "IN-HOUSE";
  $pubName = "OLIMOB";
  $serviceName = "BEYOND_LIFE_STYLE";
  $country = "PALESTINE";
  $msisdn = $_GET['msisdn'];



  $fp = fopen("Request_" . $time_india_one, "a");

  $url = "http://jawwal.mediaworldiq.com/dcb/API/VMS-DCBSubscription/actions/sendPincode?user=arshiya&password=@rsh!y@22&msisdn=$msisdn&shortcode=37788&serviceId=11161&spId=5249";

  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

  curl_setopt($ch, CURLOPT_URL, "$url");
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

  $result = curl_exec($ch);

  curl_close($ch);



  // $result=json_encode($result);
  $check = json_decode($result, true);
  $finalResult = json_encode($check);
  $code = $check['status'];
  $reason = $check['msg'];

  fwrite($fp, "\n[$time_india_one] Received $msisdn hitting the url $url and Received $result \n");

  // $sql = "INSERT INTO `palestineBeyondLifeStylePinRequest` (`cid`,`pubName`,`msisdn`,`result`,`status`,`indiaTimeZone`)  VALUES('$cid','$pubName','$msisdn','$result','$code','$time_india_one')";
  // mysql_query($sql);

  $sql_subscription = "INSERT INTO `in_app_pin_request` (`serviceId`,`advName`,`pubName`,`serviceName`,`country`,`msisdn`,`result`,`status`,`finalStatus`,`serviceDate`,`date`)  VALUES('$serviceId','$advName','$pubName','$serviceName','$country','$msisdn','$json_response','$message','$subscriptionResult','$serviceDate','$time_india_one')";
  mysql_query($sql_subscription);

  fwrite($fp, "\n[$time_india_one] Received $msisdn hitting the url $url with  Received $result and trigger Query $sql \n");


  if ($code == "Success") {
    echo json_encode(array('response' => 'SUCCESS', 'errorMessage' => 'OK'));
    exit();
  } else {
    echo json_encode(array('response' => 'Fail', 'errorMessage' => $reason));

    exit();
  }
  ?>