

  <?php
  include("connect.php");
  date_default_timezone_set('Asia/Kolkata');
  $time_india_one = date("Y-m-d H:i:s");
  date_default_timezone_set('Asia/Bahrain');
  $serviceDate = date("Y-m-d H:i:s");
  $msisdn = $_GET['msisdn'];
  $serviceId = "ARSH0084";
  $advName = "mobility";
  $pubName = "olimob";
  $serviceName = "HG";
  $country = "Bahrain";



  $fp = fopen("pin_Request_" . $time_india_one, "a");
  fwrite($fp, "\n[$time_india_one] Received $msisdn \n");

  $data_Raw = array(
    "msisdn" => "$msisdn",
    "packName" => "HG",
    "channel" => "WEB"
  );

  $payload = json_encode($data_Raw);


  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

  curl_setopt($ch, CURLOPT_URL, 'http://223.30.211.119/OtpWraper/batelco/sendotp');
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, "$payload");

  $headers = array();
  $headers[] = 'Authorization: Basic YWRtaW46YWJjZGVAMTIz';
  $headers[] = 'Content-Type: application/json';
  $headers[] = 'Cookie: JSESSIONID=2800CF76CA6AB2A6AE49D70A064BF95F; JSESSIONID=2099DC941ABD16967AAA41D6180B764D';
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

  $result = curl_exec($ch);

  curl_close($ch);

  $subscriptionResult = json_encode($result);
  $check = json_decode($result, true);
  //echo "<pre>";
  //print_r($check);
  $code = $check['result'];
  $reason = $check['Description'];

  fwrite($fp, "\n[$time_india_one] Received $msisdn hitting the url $url with payload $payload Received $subscriptionResult\n");
  fclose($fp);

  $newsql = "INSERT INTO `in_app_pin_request` (`serviceId`,`advName`,`pubName`,`serviceName`,`country`,`msisdn`,`result`,`status`,`finalStatus`,`serviceDate`,`date`)  VALUES('$serviceId','$advName','$pubName','$serviceName','$country','$msisdn','$result','$code','$reason','$serviceDate','$time_india_one')";
  mysql_query($newsql);


  if ($code == "Success") {
    echo json_encode(array('response' => 'SUCCESS', 'errorMessage' => 'OK'));
    exit();
  } else {

    echo json_encode(array('response' => 'Fail', 'errorMessage' => 'INVALID_MSISDN'));
    exit();
  }


  ?>