<?php
include("connect.php");
date_default_timezone_set('Asia/Kolkata');
$time_india_one = date("Y-m-d H:i:s");
date_default_timezone_set('Asia/Qatar');
$serviceDate = date("Y-m-d H:i:s");
$msisdn = $_GET['msisdn'];
$pin = $_GET['pin'];
$serviceId = "ARSH0108";
$advName = "FOREST";
$pubName = "OLIMOB";
$serviceName = "Gamemania";
$country = "QATAR-VODA";
$key = "rHpfduIPcAkfVpBbajzlPWApGoWX6QmqcEA411F5";
$userAgent = $_SERVER['HTTP_USER_AGENT'];
$user = Urlencode($userAgent);

$sql="SELECT `finalStatus` from `in_app_pin_request` where `msisdn`='".$msisdn."' and `serviceId`='ARSH0101' order by id desc limit 1";
          $result=mysql_query($sql);
          $row = mysql_fetch_array($result);
          $transactionID=$row['finalStatus'];  



$fp = fopen("pin_get_verify" . $time_india_one, "a");

$url = "http://qa.gamemania.io/sub/Campaign/InAppSubscription?key=$key&msisdn=$msisdn&pin=$pin&transactionId=$transactionID&UA=$user";

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "$url");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);
curl_close($ch);

//  echo $result ;
//  die();

$check = json_decode($result, true);

$code = $check['response'];
$reason = $check['errorMessage'];


fwrite($fp, "\n[$time_india_one] Received $msisdn hit the api $url and Received $result \n");

if ($code == "SUCCESS") {

    $results = file_get_contents('http://beyondhealth.info/Services/Filter/chk.php?id=342&op=Gamemania_Forest_olimob_Qatar_voda');

    if ($results == 0) //MEANS PASS
    {
        $panda = "PASSED";
        $sql = "INSERT INTO  `in_app_pin_verify` (`serviceId`,`advName`,`pubName`,`serviceName`,`country`,`msisdn`,`otp`,`result`,`status`,`finalStatus`,`serviceDate`,`date`)  VALUES('$serviceId','$advName','$pubName','$serviceName','$country','$msisdn','$pin','$result','$panda','$response','$serviceDate','$time_india_one')";
        mysql_query($sql);

        fwrite($fp, "\n $time_india_one Received $msisdn  Query $sql \n");

        echo json_encode(array('response' => 'SUCCESS', 'errorMessage' => 'OK'));
        exit();
    }

    if ($results == 1) //MEANS BLOCK

    {
        $panda = "BLOCK";
        $sql = "INSERT INTO  `in_app_pin_verify` (`serviceId`,`advName`,`pubName`,`serviceName`,`country`,`msisdn`,`otp`,`result`,`status`,`finalStatus`,`serviceDate`,`date`)  VALUES('$serviceId','$advName','$pubName','$serviceName','$country','$msisdn','$pin','$result','$panda','$response','$serviceDate','$time_india_one')";
        mysql_query($sql);
        fwrite($fp, "\n $time_india_one Received $msisdn Query $sql \n");

        echo json_encode(array('response' => 'Fail', 'errorMessage' => 'Multiple Hits on msisdn'));
        exit();
    }
} else {
    $sql = "INSERT INTO  `in_app_pin_verify` (`serviceId`,`advName`,`pubName`,`serviceName`,`country`,`msisdn`,`otp`,`result`,`status`,`finalStatus`,`serviceDate`,`date`)  VALUES('$serviceId','$advName','$pubName','$serviceName','$country','$msisdn','$pin','$result','$code','$reason','$serviceDate','$time_india_one')";
    mysql_query($sql);

    fwrite($fp, "\n $time_india_one Received $msisdn  Query  $sql \n");
    echo json_encode(array('response' => 'Fail', 'errorMessage' => $reason));
}

