<?php
include("connect.php");
date_default_timezone_set('Asia/Kolkata');
$time_india_one = date("Y-m-d H:i:s");
date_default_timezone_set('Asia/Qatar');
$serviceDate = date("Y-m-d H:i:s");
$msisdn = $_GET['msisdn'];
$serviceId = "ARSH0108";
$advName = "Forest";
$pubName = "OLIMOB";
$serviceName = "Gamemania";
$country = "QATAR";
$key = "rHpfduIPcAkfVpBbajzlPWApGoWX6QmqcEA411F5";
$userAgent = $_SERVER['HTTP_USER_AGENT'];
$user=Urlencode ($userAgent);
$transactionID=rand();


$fp = fopen("pin_get_request" .$time_india_one, "a");

$url = "http://qa.gamemania.io/sub/Campaign/InAppSendPin?key=$key&msisdn=$msisdn&transactionId=$transactionID&UA=$user";



// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "$url");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);
curl_close($ch);

// echo $result ;
// die();

$check = json_decode($result, true);

$code = $check['response'];
$reason = $check['errorMessage'];


$sql_subscription = "INSERT INTO `in_app_pin_request` (`serviceId`,`advName`,`pubName`,`serviceName`,`country`,`msisdn`,`result`,`status`,`finalStatus`,`serviceDate`,`date`)  VALUES('$serviceId','$advName','$pubName','$serviceName','$country','$msisdn','$result','$code','$transactionID','$serviceDate','$time_india_one')";
mysql_query($sql_subscription);


fwrite($fp, "\n[$time_india_one] Received $msisdn hit the api $url and Received $result  and Query $sql_subscription\n");

if ($code == "SUCCESS") {

    echo json_encode(array('response' => 'SUCCESS', 'errorMessage' => 'OK'));
} else {

    echo json_encode(array('response' => 'Fail', 'errorMessage' => 'wrong msisdn'));
}
