<?php
include("connect.php");
date_default_timezone_set('Asia/Kolkata');
$time_india_one = date("Y-m-d H:i:s");
date_default_timezone_set('Asia/Baghdad');
$serviceDate = date("Y-m-d H:i:s");
$serviceId = "ARSH0132";
$advName = "INHOUSE";
$pubName = "AFFLINK";
$serviceName = "gamespro";
$country = "IRAQ_ZAIN";
$ip = $_SERVER['REMOTE_ADDR'];

$msisdn = $_GET['msisdn'];
$otp = $_GET['pin'];


$fp = fopen("Verify_" . $time_india_one, "a");


$sql = "SELECT `finalStatus` from `in_app_pin_request` where `msisdn`='" . $msisdn . "' and serviceId='ARSH0132'  order by id desc limit 1";
$result = mysql_query($sql);
$row = mysql_fetch_array($result);
$tid = $row['finalStatus'];


fwrite($fp, "\n[$time_india_one] Received $msisdn with OTP $otp , tid $tid \n");


$url = "http://vascld-cgw.mcomviva.com:8093/API/OTPValidateActionApp?msisdn=$msisdn&request_locale=en&reqMode=APP&transId=$tid&productName=Mooditt+Games+Pro&pPrice=200&pVal=1&Otp=$otp&contentId=default&CpId=WAPKD-08&srcIP=$ip&opId=102&optionalParameter1=1001&optionalParameter2=1002";


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "$url");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($ch);
curl_close($ch);

$resultLoad = simplexml_load_string($result);
$resultEncode = json_encode($resultLoad);
// Convert into associative array
$resultArray = json_decode($resultEncode, true);
$errorCode = $resultArray['error_code'];
$errorDesc = $resultArray['errorDesc'];




fwrite($fp, "\n[$time_india_one] Received $msisdn with $url and result $result and status $errorDesc'\n");

if ($errorCode == "0") {


    $results = file_get_contents('http://beyondhealth.info/Services/Filter/chk.php?id=368&op=GAMESPRO_IRAQ_ZAIN_AFFLINK_API');

    if ($results == 0) //MEANS PASS
    {
        $panda = "PASSED";
        $sql = "INSERT INTO  `in_app_pin_verify` (`serviceId`,`advName`,`pubName`,`serviceName`,`country`,`msisdn`,`otp`,`result`,`status`,`finalStatus`,`serviceDate`,`date`)  VALUES('$serviceId','$advName','$pubName','$serviceName','$country','$msisdn','$otp','$resultEncode','$panda','$errorCode','$serviceDate','$time_india_one')";
        mysql_query($sql);

        fwrite($fp, "\n $time_india_one Received $msisdn  Query $sql \n");

        echo json_encode(array('response' => 'SUCCESS', 'errorMessage' => 'OK'));
        exit();
    }

    if ($results == 1) //MEANS BLOCK

    {
        $panda = "BLOCK";
        $sql = "INSERT INTO  `in_app_pin_verify` (`serviceId`,`advName`,`pubName`,`serviceName`,`country`,`msisdn`,`otp`,`result`,`status`,`finalStatus`,`serviceDate`,`date`)  VALUES('$serviceId','$advName','$pubName','$serviceName','$country','$msisdn','$otp','$resultEncode','$panda','$errorCode','$serviceDate','$time_india_one')";
        mysql_query($sql);
        fwrite($fp, "\n $time_india_one Received $msisdn Query $sql \n");

        echo json_encode(array('response' => 'Fail', 'errorMessage' => 'Multiple Hits on msisdn'));

        exit();
    }
} else {
    $sql = "INSERT INTO  `in_app_pin_verify` (`serviceId`,`advName`,`pubName`,`serviceName`,`country`,`msisdn`,`otp`,`result`,`status`,`finalStatus`,`serviceDate`,`date`)  VALUES('$serviceId','$advName','$pubName','$serviceName','$country','$msisdn','$otp','$resultEncode','$errorDesc','$errorCode','$serviceDate','$time_india_one')";
    mysql_query($sql);

    fwrite($fp, "\n $time_india_one Received $msisdn  Query  $sql \n");
    echo json_encode(array('response' => 'Fail', 'errorMessage' => 'wrong pin'));
}
